# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2025 StarField Xu <air_jinkela@163.com>

ccflags-y += -Wall

obj-$(CONFIG_RTL837X_DSA) += rtl8372n_dsa.o
rtl8372n_dsa-objs := rtl8372n.o rtl837x_mdio.o rtl837x_common.o rtl8372n_phy.o
