## This file contains files and directories that should
## be preserved during an upgrade.

# /etc/example.conf
# /etc/openvpn/

/etc/rc.local
/etc/crontabs/root
/etc/uhttpd.crt
/etc/uhttpd.key
/etc/resolv.conf
/etc/modules.conf
/etc/librenms/
/etc/sysctl.conf
/etc/dropbear/
/root/
/etc/ethers
/etc/librenms/
/root/
/etc/config/snmpd
/etc/init.d/roaming-nr
/etc/config/dawn
/usr/sbin/lowsig-kick.sh
/etc/init.d/lowsig-kick
/etc/profile.d/99-sysinfo.sh
/etc/hotplug.d/net/99-wds-vlan192
/etc/librenms
/usr/bin/peer-watch.sh
/etc/log-flush.sh
/etc/log-flush.status
